name: mi_musica_app
description: "Aplicación de música optimizada con descarga y texto a voz"
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Audio y TTS
  just_audio: ^0.9.46
  flutter_tts: ^3.8.5
  
  # Almacenamiento y permisos
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  
  # HTTP simplificado
  http: ^0.13.6
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true